from typing import List, Dict, Any

class Dota7_40B:
    """ Holds data about the game as of 7.40b
    """

    HEROES: List[Dict[str, Any]] = [
        {'id': 1, 'name': 'npc_dota_hero_antimage', 'displayName': 'Anti-Mage', 'shortName': 'antimage', 'aliases': ['am', 'wei']},
        {'id': 2, 'name': 'npc_dota_hero_axe', 'displayName': 'Axe', 'shortName': 'axe', 'aliases': []},
        {'id': 3, 'name': 'npc_dota_hero_bane', 'displayName': 'Bane', 'shortName': 'bane', 'aliases': []},
        {'id': 4, 'name': 'npc_dota_hero_bloodseeker', 'displayName': 'Bloodseeker', 'shortName': 'bloodseeker', 'aliases': ['bs']},
        {'id': 5, 'name': 'npc_dota_hero_crystal_maiden', 'displayName': 'Crystal Maiden', 'shortName': 'crystal_maiden', 'aliases': ['cm', 'rylai', 'wolf']},
        {'id': 6, 'name': 'npc_dota_hero_drow_ranger', 'displayName': 'Drow Ranger', 'shortName': 'drow_ranger', 'aliases': ['Traxex']},
        {'id': 7, 'name': 'npc_dota_hero_earthshaker', 'displayName': 'Earthshaker', 'shortName': 'earthshaker', 'aliases': ['es', 'Raigor']},
        {'id': 8, 'name': 'npc_dota_hero_juggernaut', 'displayName': 'Juggernaut', 'shortName': 'juggernaut', 'aliases': ['Yurnero']},
        {'id': 9, 'name': 'npc_dota_hero_mirana', 'displayName': 'Mirana', 'shortName': 'mirana', 'aliases': ['Princess', 'Moon', 'potm']},
        {'id': 10, 'name': 'npc_dota_hero_morphling', 'displayName': 'Morphling', 'shortName': 'morphling', 'aliases': []},
        {'id': 11, 'name': 'npc_dota_hero_nevermore', 'displayName': 'Shadow Fiend', 'shortName': 'nevermore', 'aliases': ['sf', 'nevermore']},
        {'id': 12, 'name': 'npc_dota_hero_phantom_lancer', 'displayName': 'Phantom Lancer', 'shortName': 'phantom_lancer', 'aliases': ['pl', 'Azwraith']},
        {'id': 13, 'name': 'npc_dota_hero_puck', 'displayName': 'Puck', 'shortName': 'puck', 'aliases': ['Faerie Dragon', 'fd']},
        {'id': 14, 'name': 'npc_dota_hero_pudge', 'displayName': 'Pudge', 'shortName': 'pudge', 'aliases': ['Toy Butcher']},
        {'id': 15, 'name': 'npc_dota_hero_razor', 'displayName': 'Razor', 'shortName': 'razor', 'aliases': ['Lightning Revenant']},
        {'id': 16, 'name': 'npc_dota_hero_sand_king', 'displayName': 'Sand King', 'shortName': 'sand_king', 'aliases': ['sk', 'Crixalis']},
        {'id': 17, 'name': 'npc_dota_hero_storm_spirit', 'displayName': 'Storm Spirit', 'shortName': 'storm_spirit', 'aliases': ['ss', 'raijin', 'thunderkeg']},
        {'id': 18, 'name': 'npc_dota_hero_sven', 'displayName': 'Sven', 'shortName': 'sven', 'aliases': ['Rogue Knight']},
        {'id': 19, 'name': 'npc_dota_hero_tiny', 'displayName': 'Tiny', 'shortName': 'tiny', 'aliases': ['Stone Giant']},
        {'id': 20, 'name': 'npc_dota_hero_vengefulspirit', 'displayName': 'Vengeful Spirit', 'shortName': 'vengefulspirit', 'aliases': ['vs', 'Shendelzare']},
        {'id': 21, 'name': 'npc_dota_hero_windrunner', 'displayName': 'Windranger', 'shortName': 'windrunner', 'aliases': ['wr', 'Lyralei']},
        {'id': 22, 'name': 'npc_dota_hero_zuus', 'displayName': 'Zeus', 'shortName': 'zuus', 'aliases': ['Lord of Heaven']},
        {'id': 23, 'name': 'npc_dota_hero_kunkka', 'displayName': 'Kunkka', 'shortName': 'kunkka', 'aliases': ['Admiral']},
        {'id': 25, 'name': 'npc_dota_hero_lina', 'displayName': 'Lina', 'shortName': 'lina', 'aliases': ['slayer']},
        {'id': 26, 'name': 'npc_dota_hero_lion', 'displayName': 'Lion', 'shortName': 'lion', 'aliases': ['Demon Witch']},
        {'id': 27, 'name': 'npc_dota_hero_shadow_shaman', 'displayName': 'Shadow Shaman', 'shortName': 'shadow_shaman', 'aliases': ['ss', 'Rhasta']},
        {'id': 28, 'name': 'npc_dota_hero_slardar', 'displayName': 'Slardar', 'shortName': 'slardar', 'aliases': ['Slithereen Guard']},
        {'id': 29, 'name': 'npc_dota_hero_tidehunter', 'displayName': 'Tidehunter', 'shortName': 'tidehunter', 'aliases': ['th', 'Leviathan']},
        {'id': 30, 'name': 'npc_dota_hero_witch_doctor', 'displayName': 'Witch Doctor', 'shortName': 'witch_doctor', 'aliases': ['wd', 'Zharvakko']},
        {'id': 31, 'name': 'npc_dota_hero_lich', 'displayName': 'Lich', 'shortName': 'lich', 'aliases': ['Ethreain']},
        {'id': 32, 'name': 'npc_dota_hero_riki', 'displayName': 'Riki', 'shortName': 'riki', 'aliases': ['Stealth Assassin', 'sa']},
        {'id': 33, 'name': 'npc_dota_hero_enigma', 'displayName': 'Enigma', 'shortName': 'enigma', 'aliases': []},
        {'id': 34, 'name': 'npc_dota_hero_tinker', 'displayName': 'Tinker', 'shortName': 'tinker', 'aliases': ['Boush']},
        {'id': 35, 'name': 'npc_dota_hero_sniper', 'displayName': 'Sniper', 'shortName': 'sniper', 'aliases': ['Kardel Sharpeye']},
        {'id': 36, 'name': 'npc_dota_hero_necrolyte', 'displayName': 'Necrophos', 'shortName': 'necrolyte', 'aliases': ['Rotundjere']},
        {'id': 37, 'name': 'npc_dota_hero_warlock', 'displayName': 'Warlock', 'shortName': 'warlock', 'aliases': ['wl', 'Demnok Lannik']},
        {'id': 38, 'name': 'npc_dota_hero_beastmaster', 'displayName': 'Beastmaster', 'shortName': 'beastmaster', 'aliases': ['bm']},
        {'id': 39, 'name': 'npc_dota_hero_queenofpain', 'displayName': 'Queen of Pain', 'shortName': 'queenofpain', 'aliases': ['qop', 'Akasha']},
        {'id': 40, 'name': 'npc_dota_hero_venomancer', 'displayName': 'Venomancer', 'shortName': 'venomancer', 'aliases': ['Lesale']},
        {'id': 41, 'name': 'npc_dota_hero_faceless_void', 'displayName': 'Faceless Void', 'shortName': 'faceless_void', 'aliases': ['fv']},
        {'id': 42, 'name': 'npc_dota_hero_skeleton_king', 'displayName': 'Wraith King', 'shortName': 'skeleton_king', 'aliases': ['sk', 'snk', 'wk', 'skeleton', 'one true king', 'Ostarion']},
        {'id': 43, 'name': 'npc_dota_hero_death_prophet', 'displayName': 'Death Prophet', 'shortName': 'death_prophet', 'aliases': ['dp', 'Krobelus']},
        {'id': 44, 'name': 'npc_dota_hero_phantom_assassin', 'displayName': 'Phantom Assassin', 'shortName': 'phantom_assassin', 'aliases': ['pa', 'mortred']},
        {'id': 45, 'name': 'npc_dota_hero_pugna', 'displayName': 'Pugna', 'shortName': 'pugna', 'aliases': []},
        {'id': 46, 'name': 'npc_dota_hero_templar_assassin', 'displayName': 'Templar Assassin', 'shortName': 'templar_assassin', 'aliases': ['ta', 'Lanaya']},
        {'id': 47, 'name': 'npc_dota_hero_viper', 'displayName': 'Viper', 'shortName': 'viper', 'aliases': ['Netherdrake']},
        {'id': 48, 'name': 'npc_dota_hero_luna', 'displayName': 'Luna', 'shortName': 'luna', 'aliases': ['Moon Rider']},
        {'id': 49, 'name': 'npc_dota_hero_dragon_knight', 'displayName': 'Dragon Knight', 'shortName': 'dragon_knight', 'aliases': ['dk', 'davion', "dragon's blood"]},
        {'id': 50, 'name': 'npc_dota_hero_dazzle', 'displayName': 'Dazzle', 'shortName': 'dazzle', 'aliases': []},
        {'id': 51, 'name': 'npc_dota_hero_rattletrap', 'displayName': 'Clockwerk', 'shortName': 'rattletrap', 'aliases': ['Rattletrap', 'cw']},
        {'id': 52, 'name': 'npc_dota_hero_leshrac', 'displayName': 'Leshrac', 'shortName': 'leshrac', 'aliases': ['ts']},
        {'id': 53, 'name': 'npc_dota_hero_furion', 'displayName': "Nature's Prophet", 'shortName': 'furion', 'aliases': ['np']},
        {'id': 54, 'name': 'npc_dota_hero_life_stealer', 'displayName': 'Lifestealer', 'shortName': 'life_stealer', 'aliases': ['ls', 'Naix']},
        {'id': 55, 'name': 'npc_dota_hero_dark_seer', 'displayName': 'Dark Seer', 'shortName': 'dark_seer', 'aliases': ['ds', 'Ishkafel']},
        {'id': 56, 'name': 'npc_dota_hero_clinkz', 'displayName': 'Clinkz', 'shortName': 'clinkz', 'aliases': []},
        {'id': 57, 'name': 'npc_dota_hero_omniknight', 'displayName': 'Omniknight', 'shortName': 'omniknight', 'aliases': ['Purist Thunderwrath']},
        {'id': 58, 'name': 'npc_dota_hero_enchantress', 'displayName': 'Enchantress', 'shortName': 'enchantress', 'aliases': ['Aiushtha']},
        {'id': 59, 'name': 'npc_dota_hero_huskar', 'displayName': 'Huskar', 'shortName': 'huskar', 'aliases': []},
        {'id': 60, 'name': 'npc_dota_hero_night_stalker', 'displayName': 'Night Stalker', 'shortName': 'night_stalker', 'aliases': ['ns', 'Balanar']},
        {'id': 61, 'name': 'npc_dota_hero_broodmother', 'displayName': 'Broodmother', 'shortName': 'broodmother', 'aliases': ['bm', 'Arachnia', 'spider']},
        {'id': 62, 'name': 'npc_dota_hero_bounty_hunter', 'displayName': 'Bounty Hunter', 'shortName': 'bounty_hunter', 'aliases': ['bh']},
        {'id': 63, 'name': 'npc_dota_hero_weaver', 'displayName': 'Weaver', 'shortName': 'weaver', 'aliases': ['nw', 'Skitskurr']},
        {'id': 64, 'name': 'npc_dota_hero_jakiro', 'displayName': 'Jakiro', 'shortName': 'jakiro', 'aliases': ['thd', 'twin headed dragon']},
        {'id': 65, 'name': 'npc_dota_hero_batrider', 'displayName': 'Batrider', 'shortName': 'batrider', 'aliases': ['br']},
        {'id': 66, 'name': 'npc_dota_hero_chen', 'displayName': 'Chen', 'shortName': 'chen', 'aliases': ['Holy Knight']},
        {'id': 67, 'name': 'npc_dota_hero_spectre', 'displayName': 'Spectre', 'shortName': 'spectre', 'aliases': ['Mercurial']},
        {'id': 68, 'name': 'npc_dota_hero_ancient_apparition', 'displayName': 'Ancient Apparition', 'shortName': 'ancient_apparition', 'aliases': ['aa']},
        {'id': 69, 'name': 'npc_dota_hero_doom_bringer', 'displayName': 'Doom', 'shortName': 'doom_bringer', 'aliases': ['db']},
        {'id': 70, 'name': 'npc_dota_hero_ursa', 'displayName': 'Ursa', 'shortName': 'ursa', 'aliases': ['Ulfsaar']},
        {'id': 71, 'name': 'npc_dota_hero_spirit_breaker', 'displayName': 'Spirit Breaker', 'shortName': 'spirit_breaker', 'aliases': ['sb', 'Barathrum']},
        {'id': 72, 'name': 'npc_dota_hero_gyrocopter', 'displayName': 'Gyrocopter', 'shortName': 'gyrocopter', 'aliases': ['Aurel']},
        {'id': 73, 'name': 'npc_dota_hero_alchemist', 'displayName': 'Alchemist', 'shortName': 'alchemist', 'aliases': ['Razzil']},
        {'id': 74, 'name': 'npc_dota_hero_invoker', 'displayName': 'Invoker', 'shortName': 'invoker', 'aliases': ['kid']},
        {'id': 75, 'name': 'npc_dota_hero_silencer', 'displayName': 'Silencer', 'shortName': 'silencer', 'aliases': ['Nortrom']},
        {'id': 76, 'name': 'npc_dota_hero_obsidian_destroyer', 'displayName': 'Outworld Destroyer', 'shortName': 'obsidian_destroyer', 'aliases': ['od', 'Harbinger']},
        {'id': 77, 'name': 'npc_dota_hero_lycan', 'displayName': 'Lycan', 'shortName': 'lycan', 'aliases': ['Banehallow', 'wolf']},
        {'id': 78, 'name': 'npc_dota_hero_brewmaster', 'displayName': 'Brewmaster', 'shortName': 'brewmaster', 'aliases': ['bm', 'Mangix']},
        {'id': 79, 'name': 'npc_dota_hero_shadow_demon', 'displayName': 'Shadow Demon', 'shortName': 'shadow_demon', 'aliases': ['sd']},
        {'id': 80, 'name': 'npc_dota_hero_lone_druid', 'displayName': 'Lone Druid', 'shortName': 'lone_druid', 'aliases': ['ld', 'bear', 'Sylla']},
        {'id': 81, 'name': 'npc_dota_hero_chaos_knight', 'displayName': 'Chaos Knight', 'shortName': 'chaos_knight', 'aliases': ['ck']},
        {'id': 82, 'name': 'npc_dota_hero_meepo', 'displayName': 'Meepo', 'shortName': 'meepo', 'aliases': ['geomancer', 'meepwn']},
        {'id': 83, 'name': 'npc_dota_hero_treant', 'displayName': 'Treant Protector', 'shortName': 'treant', 'aliases': []},
        {'id': 84, 'name': 'npc_dota_hero_ogre_magi', 'displayName': 'Ogre Magi', 'shortName': 'ogre_magi', 'aliases': ['om']},
        {'id': 85, 'name': 'npc_dota_hero_undying', 'displayName': 'Undying', 'shortName': 'undying', 'aliases': ['Dirge']},
        {'id': 86, 'name': 'npc_dota_hero_rubick', 'displayName': 'Rubick', 'shortName': 'rubick', 'aliases': ['rubick']},
        {'id': 87, 'name': 'npc_dota_hero_disruptor', 'displayName': 'Disruptor', 'shortName': 'disruptor', 'aliases': ['disruptor']},
        {'id': 88, 'name': 'npc_dota_hero_nyx_assassin', 'displayName': 'Nyx Assassin', 'shortName': 'nyx_assassin', 'aliases': ['na']},
        {'id': 89, 'name': 'npc_dota_hero_naga_siren', 'displayName': 'Naga Siren', 'shortName': 'naga_siren', 'aliases': ['naga', 'Slithice']},
        {'id': 90, 'name': 'npc_dota_hero_keeper_of_the_light', 'displayName': 'Keeper of the Light', 'shortName': 'keeper_of_the_light', 'aliases': ['keeper', 'ezalor', 'kotl']},
        {'id': 91, 'name': 'npc_dota_hero_wisp', 'displayName': 'Io', 'shortName': 'wisp', 'aliases': ['wisp']},
        {'id': 92, 'name': 'npc_dota_hero_visage', 'displayName': 'Visage', 'shortName': 'visage', 'aliases': ['visage', 'Necrolic']},
        {'id': 93, 'name': 'npc_dota_hero_slark', 'displayName': 'Slark', 'shortName': 'slark', 'aliases': ['slark']},
        {'id': 94, 'name': 'npc_dota_hero_medusa', 'displayName': 'Medusa', 'shortName': 'medusa', 'aliases': ['medusa', 'gorgon']},
        {'id': 95, 'name': 'npc_dota_hero_troll_warlord', 'displayName': 'Troll Warlord', 'shortName': 'troll_warlord', 'aliases': ['troll', 'jahrakal']},
        {'id': 96, 'name': 'npc_dota_hero_centaur', 'displayName': 'Centaur Warrunner', 'shortName': 'centaur', 'aliases': ['centaur']},
        {'id': 97, 'name': 'npc_dota_hero_magnataur', 'displayName': 'Magnus', 'shortName': 'magnataur', 'aliases': ['magnataur', 'magnus']},
        {'id': 98, 'name': 'npc_dota_hero_shredder', 'displayName': 'Timbersaw', 'shortName': 'shredder', 'aliases': ['Rizzrack', 'Shredder', 'Timbersaw']},
        {'id': 99, 'name': 'npc_dota_hero_bristleback', 'displayName': 'Bristleback', 'shortName': 'bristleback', 'aliases': ['Rigwarl', 'bb']},
        {'id': 100, 'name': 'npc_dota_hero_tusk', 'displayName': 'Tusk', 'shortName': 'tusk', 'aliases': ['Ymir']},
        {'id': 101, 'name': 'npc_dota_hero_skywrath_mage', 'displayName': 'Skywrath Mage', 'shortName': 'skywrath_mage', 'aliases': ['sm', 'Dragonus']},
        {'id': 102, 'name': 'npc_dota_hero_abaddon', 'displayName': 'Abaddon', 'shortName': 'abaddon', 'aliases': ['Abaddon']},
        {'id': 103, 'name': 'npc_dota_hero_elder_titan', 'displayName': 'Elder Titan', 'shortName': 'elder_titan', 'aliases': ['TC', 'Cairne', 'et']},
        {'id': 104, 'name': 'npc_dota_hero_legion_commander', 'displayName': 'Legion Commander', 'shortName': 'legion_commander', 'aliases': ['Tresdin', 'Legion', 'lc']},
        {'id': 105, 'name': 'npc_dota_hero_techies', 'displayName': 'Techies', 'shortName': 'techies', 'aliases': ['Squee', 'Spleen', 'Spoon']},
        {'id': 106, 'name': 'npc_dota_hero_ember_spirit', 'displayName': 'Ember Spirit', 'shortName': 'ember_spirit', 'aliases': ['Xin', 'Ember', 'es']},
        {'id': 107, 'name': 'npc_dota_hero_earth_spirit', 'displayName': 'Earth Spirit', 'shortName': 'earth_spirit', 'aliases': ['es', 'Kaolin', 'Earth']},
        {'id': 108, 'name': 'npc_dota_hero_abyssal_underlord', 'displayName': 'Underlord', 'shortName': 'abyssal_underlord', 'aliases': ['PitLord', 'Azgalor', 'ul']},
        {'id': 109, 'name': 'npc_dota_hero_terrorblade', 'displayName': 'Terrorblade', 'shortName': 'terrorblade', 'aliases': ['tb']},
        {'id': 110, 'name': 'npc_dota_hero_phoenix', 'displayName': 'Phoenix', 'shortName': 'phoenix', 'aliases': ['ph']},
        {'id': 111, 'name': 'npc_dota_hero_oracle', 'displayName': 'Oracle', 'shortName': 'oracle', 'aliases': ['ora', 'Nerif']},
        {'id': 112, 'name': 'npc_dota_hero_winter_wyvern', 'displayName': 'Winter Wyvern', 'shortName': 'winter_wyvern', 'aliases': ['ww', 'Auroth']},
        {'id': 113, 'name': 'npc_dota_hero_arc_warden', 'displayName': 'Arc Warden', 'shortName': 'arc_warden', 'aliases': ['zet', 'aw']},
        {'id': 114, 'name': 'npc_dota_hero_monkey_king', 'displayName': 'Monkey King', 'shortName': 'monkey_king', 'aliases': ['mk', 'Sun Wukong']},
        {'id': 119, 'name': 'npc_dota_hero_dark_willow', 'displayName': 'Dark Willow', 'shortName': 'dark_willow', 'aliases': ['dw', 'Mireska']},
        {'id': 120, 'name': 'npc_dota_hero_pangolier', 'displayName': 'Pangolier', 'shortName': 'pangolier', 'aliases': ['ar']},
        {'id': 121, 'name': 'npc_dota_hero_grimstroke', 'displayName': 'Grimstroke', 'shortName': 'grimstroke', 'aliases': ['gs']},
        {'id': 123, 'name': 'npc_dota_hero_hoodwink', 'displayName': 'Hoodwink', 'shortName': 'hoodwink', 'aliases': ['squirrel', 'hw']},
        {'id': 126, 'name': 'npc_dota_hero_void_spirit', 'displayName': 'Void Spirit', 'shortName': 'void_spirit', 'aliases': ['Void', 'VS', 'Inai']},
        {'id': 128, 'name': 'npc_dota_hero_snapfire', 'displayName': 'Snapfire', 'shortName': 'snapfire', 'aliases': ['snap', 'mortimer']},
        {'id': 129, 'name': 'npc_dota_hero_mars', 'displayName': 'Mars', 'shortName': 'mars', 'aliases': ['mars']},
        {'id': 131, 'name': 'npc_dota_hero_ringmaster', 'displayName': 'Ringmaster', 'shortName': 'ringmaster', 'aliases': ['rm', 'marionetto', 'cogliostro']},
        {'id': 135, 'name': 'npc_dota_hero_dawnbreaker', 'displayName': 'Dawnbreaker', 'shortName': 'dawnbreaker', 'aliases': ['Dawnbreaker', 'Valora']},
        {'id': 136, 'name': 'npc_dota_hero_marci', 'displayName': 'Marci', 'shortName': 'marci', 'aliases': []},
        {'id': 137, 'name': 'npc_dota_hero_primal_beast', 'displayName': 'Primal Beast', 'shortName': 'primal_beast', 'aliases': ['pb']},
        {'id': 138, 'name': 'npc_dota_hero_muerta', 'displayName': 'Muerta', 'shortName': 'muerta', 'aliases': []},
        {'id': 145, 'name': 'npc_dota_hero_kez', 'displayName': 'Kez', 'shortName': 'kez', 'aliases': ['bird samurai', 'kestrel']},
        {'id': 155, 'name': 'npc_dota_hero_largo', 'displayName': 'Largo', 'shortName': 'largo', 'aliases': ['bard_frog']}
    ]

    ITEMS: List[Dict[str, Any]] = []
